# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SonarCloud
description: >
  SonarCloud is a service operated by SonarSource, the company that develops
  and promotes open-source code quality products SonarQube and SonarLint.
baseurl: ""
# url should point to:
# - "https://about.sonarcloud.io" for PROD
# - "https://about2.sonarcloud.io" for DEV
url: "https://about.sonarcloud.io"
# service_url should point to:
# - "https://sonarcloud.io" for PROD
# - "https://lagoon2.sonarsource.com" for DEV
service_url: "https://sonarcloud.io"
logo_url: "/images/SonarCloud-white.svg"
twitter_username: sonarqube

# Build settings
markdown: kramdown
# Permalink for news
permalink: /news/:year/:month/:day/:title.html
