# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: About SonarQube.com
description: >
  SonarQube.com is a service operated by SonarSource, the company that develops
  and promotes open-source code quality products SonarQube and SonarLint.
baseurl: ""
url: "https://news.sonarqube.com"
logo_url: "/images/sonarqube.com_162px.png"
twitter_username: sonarqube

# Build settings
markdown: kramdown
# Permalink for news
permalink: /news/:year/:month/:day/:title.html
