# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SonarQube.com News
email: ""
description: >
  Stay tuned with the latest new features available on SonarQube.com and
  be informed upfront of any change or maintainance operations that might
  impact the service.
baseurl: ""
url: "https://news.sonarqube.com"
twitter_username: sonarqube

# Build settings
markdown: kramdown
